# see https://docs.searxng.org/admin/engines/settings.html#use-default-settings
use_default_settings: true
general:
  instance_name: "Joe's SearX"
search:
  autocomplete: "startpage"
  default_lang: "en-US"
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: ${SECRET}
  limiter: false  # can be disabled for a private instance
  image_proxy: true
ui:
  static_use_hash: true
  results_on_new_tab: false
redis:
  url: redis://redis:6379/0
outgoing:
  extra_proxy_timeout: 10
  using_tor_proxy: true
  proxies:
    all://:
      - socks5h://tor:9050
