# see https://docs.searxng.org/admin/engines/settings.html#use-default-settings
use_default_settings: true
general:
  instance_name: "Google but the g is like gif"
search:
  autocomplete: "google"
  default_lang: "en-US"
server:
  secret_key: ${SECRET}
  limiter: false
  image_proxy: true
ui:
  static_use_hash: true
  results_on_new_tab: false
redis:
  url: redis://redis:6379/0
outgoing:
  extra_proxy_timeout: 10
  using_tor_proxy: true
  proxies:
    all://:
      - socks5h://tor:9050
engines:
  - name: qwant
    engine: qwant
    language: en-US
  - name: duckduckgo
    engine: duckduckgo
    language: en-US
    using_tor_proxy: false